name: devsite_web
description: webpage for devsite
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  #cupertino_icons:
  http:
  # uuid:
  flutter_bloc: #state management
  logger: #for logging
  google_fonts: #fonts
  flutter_svg:
  # freezed_annotation: #freeze
  #json_annotation: #for json/toMap code generation
  # json_serializable:
  #injectable: #dependency injection
  #get_it: #service locator
  #auto_route: #routing
  simple_gradient_text: #GRADIENT
  #cached_network_image:
  #shimmer:
  flutter_animate:
  responsive_builder:
  email_validator:
  scrollable_positioned_list:
  animated_text_kit:
  provider:
  sizer:
  url_launcher:
  carousel_slider:
  material_design_icons_flutter:
  font_awesome_flutter:
  flutter_form_builder:
  mailer:
  timelines:





dev_dependencies:

  #freezed:
  #injectable_generator: # Version 2
  #auto_route_generator:

  #flutter_lints:
  #build_runner:

  #faker:
  flutter_test:
    sdk: flutter
  #mocktail:
  #bloc_test:

flutter:
  uses-material-design: true

  assets:
    #company
    - assets/images/devbutton.svg
    #gif
    - assets/gif/dev_gif_300x200_dark.gif
    - assets/gif/dev_gif_300x200_light.gif
    #cards
    - assets/images/cards/custom_card.svg
    - assets/images/cards/integration_card.svg
    - assets/images/cards/mobile_card.svg
    - assets/images/cards/refactor_card.svg
    - assets/images/cards/web_card.svg
    #client-logo
    - assets/images/client/mercedes.png
    - assets/images/client/fortech.png
    - assets/images/client/revolut.svg
    - assets/images/client/orange.svg
    - assets/images/client/eurocontrol.png
    #tools-logo
    - assets/images/tools/azure.svg
    - assets/images/tools/confluence.svg
    - assets/images/tools/docker.svg
    - assets/images/tools/flutter.svg
    - assets/images/tools/git.svg
    - assets/images/tools/gradle.svg
    - assets/images/tools/google-cloud.svg
    - assets/images/tools/intellij-idea.svg
    - assets/images/tools/java.svg
    - assets/images/tools/jira.svg
    - assets/images/tools/maven.svg
    - assets/images/tools/mysql.svg
    - assets/images/tools/postgresql.svg
    - assets/images/tools/spring-boot.svg


  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: TT-Commons
  #     fonts:
  #       - asset: assets/fonts/TT-Commons-Medium.otf
  #         style: regular

  fonts:
    - family: TT-Commons
      fonts:
        - asset: assets/fonts/TT-Commons-Medium.otf

  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
